import Head from "next/head";
import { GraphQLClient, gql } from 'graphql-request';
import { SectionOne, ContainerText, FristText, MainText, SecundaryText, AboutText, GifScroll, ProjectsCall, SectionTwo, ContainerProject, Project, ProjectImg, ProjectName, ProjectDescription, ProjectText, TextWarning, BtnContact, BtnContainer} from '../styles/index.elements'

const hygraph = new GraphQLClient(
  'https://api-sa-east-1.hygraph.com/v2/cl8kkc90t1vjv01ulbzw4a0pj/master'
);

const QUERY = gql`
{
    projects {
        id
        slug
        title
        description
        sourceUrl
        demoUrl
        projectImage {
        url
        }
    }
}
`

export async function getStaticProps() {
  const { projects } = await hygraph.request(QUERY)

  return {
    props: {
      projects
    }
  }
}

export default function Home({ projects }) {

  console.log(projects)
  return (
    <>
      <Head>
        <title>Mendonça - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionOne>
        <ContainerText>
          <FristText>Ola mundo, meu nome é</FristText>
          <MainText>Gustavo Mendonça</MainText>
          <SecundaryText>Desenvolvedor Full Stack</SecundaryText>
          <AboutText>Desenvolvedor Full Stack, com experiência de atuação como Desenvolvedor Freelancer para projetos voltados ao ambiente Web.</AboutText>
          <ProjectsCall>Veja com o que andei trabalhando.</ProjectsCall>
          <GifScroll src="./scrolldown.gif"></GifScroll>
        </ContainerText>
      </SectionOne>

      <SectionTwo>
        <ContainerProject>
          {projects.map(({ title, description, projectImage, id, sourceUrl, demoUrl }) => { 
            return (
              <>
                <Project key={id}>
                  <ProjectImg src={ projectImage.url }></ProjectImg>
                  <ProjectText>
                    <ProjectName>{ title }</ProjectName>
                    <ProjectDescription> { description } </ProjectDescription>
                    <TextWarning>Mais detalhes do projeto no README no repositorio do GITHUB</TextWarning>

                    <BtnContainer>
                      <a href={ sourceUrl }
                        target="_blank"
                        rel="noreferrer"
                        >
                          <BtnContact>
                              Github
                          </BtnContact>
                      </a>
                      <a href={ demoUrl }
                        target="_blank"
                        rel="noreferrer"
                        >
                          <BtnContact>
                              Demo
                          </BtnContact>
                      </a>
                    </BtnContainer>
                  </ProjectText>

                  
                </Project>
              </>
              )
          })}
          
        </ContainerProject>
      </SectionTwo>
    </>
  )  
}
